### ISSUE TITLE
Allow working with multiple projects from a single repository

### ISSUE THREAD

**Issue by matthiasblaesing** [redminenb/redminenb#22]
As noted in issue 21 (third comment) it is desirable to be able to work with multiple projects and a single repository definition.

The mantis netbeans plugin has a similar approach, so it might be an indicator how this could be implemented in the redmine tracker plugin.

**Comment by matthiasblaesing** [comment]
Andre - I try to finish custom field support this month - I would really appretiate it, if you could have a look at the second part of your request (supporting custom fields).

The change is a bit more experimental than this issue (i had to extend the java api to access the necessary functions).

In issue #23 this is tracked and I linked an testbuild. Thanks in advance!

**Comment by ZaLiTHkA** [comment]
I must be honest, I did actually see #23 the other day, I "watched" the issue when I saw you create it.. Things got a bit crazy when work started up again this week though, so I haven't had a chance to try it yet.

I'm very excited for this feature, it will make this plugin incredibly useful. So I'll make a point to check this tomorrow and let you know, thanks for the reminder. :)
