### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by exru** [redminenb/redminenb#24]
Is it able HTTPS protocol?
-----
I can't pass authorization by HTTPS, like this:
https://rm.freematiq.com:1443
----
Response:
Invalid response from Redmine:
com.taskadapter.redmineapi.RedmineAuthenticationException: Authorization error. Please check if you provided a valid API access key or Login and Password and REST API service is enabled on the server.

**Comment by matthiasblaesing** [comment]
Can this be closed?

**Comment by exru** [comment]
Okay!
