### ISSUE TITLE
unable to connect with java error message

### ISSUE THREAD

**Issue by onkelDad** [redminenb/redminenb#26]
Hi,

I've updatged my redmine plugin this morning to new version 1.6.
After that I was not able to ooperate with my tasks due to a connection problem.

In the Create Task Repository dialog I'll get an error message:

Invalid response from Redmine:
com.taskadapter.redmineapi.RedmineTransportException: Cannot fetch data from https://...my servers FQDN.../redmine/projects.json : javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

Rollback to 1.5 helped me.

regards,
Detlef

**Comment by matthiasblaesing** [comment]
You see the verification of an SSL certificate failing - I would wager some money, that your certificate is broken. Please check if installing:

http://plugins.netbeans.org/plugin/53877/ssl-certificate-exception

helps. Its not that uncommon to have broken SSL setups, But not checking and warning is beyond broken IMHO.

**Comment by onkelDad** [comment]
If self-signed equals broken, you was right.
I agree, not checking nor warning is not a good idea.

Thanks, that perfectly helped us:)

Please reject/close this issue.

**Comment by matthiasblaesing** [comment]
Thank you for verifying and yes your right. I just realized, that I read a few too many discussions around SSL and certificates. :-)
