### ISSUE TITLE
How buid it in windows?

### ISSUE THREAD

**Issue by Slavenin** [redminenb/redminenb#30]
Perhaps it should be added builded version?

This
> Just open the redminenb/dev directory in netbeans via "Open Project" and you are good to go.

not work. Folder not open as project

**Comment by matthiasblaesing** [comment]
Sorry I don't understand your request.

1. redminenb is a maven project, so the built-in maven support from netbeans takes care to open it as project. I checked with a clean netbeans 8.0.2 and it works. What version are you using?
2. pre-built version of the plugins are available through the plugin portal / update center from netbeans (http://plugins.netbeans.org/plugin/55824/redminenb) and on git hub: https://github.com/redminenb/redminenb/releases

Please note: The first netbeans version this plugin can be used with is 8! Prior version don't offer the necessary apis.

**Comment by Slavenin** [comment]
Sorry, did not notice the builded version releases.
