### ISSUE TITLE
htaccess authentication

### ISSUE THREAD

**Issue by soraver** [redminenb/redminenb#33]
I'm trying to setup a connection on a redmine that has htaccess authentication like this:
http://user:password@redmine.example.com/
and it gives me an error. When i disable the authentication it works.

**Comment by matthiasblaesing** [comment]
I asume you mean an additional authentication like the bugzilla plugin supports:

![auswahl_003](https://cloud.githubusercontent.com/assets/2179736/7379882/584a5626-edf8-11e4-9ca8-e1a48d4805a8.png)

This should be totally doable.

**Comment by matthiasblaesing** [comment]
Please give me either an example of an installation that is modified the way you describe or point me a thus configured installation. I have some doubts that such a setup could work.

The authentication in redmine-REST api is using  basic auth when using username/password authentication. So if enabled on apache level both layers will collide - it might only work if redmine users and apache users are identical, which in turn makes me wonder why anybody would want such a setup.

According to the documentation:

http://www.redmine.org/projects/redmine/wiki/Rest_api#Authentication

even for key based authentication basic auth scheme is used.

All in: please make a valid case where it is sensible to expect this setup at all.

**Comment by soraver** [comment]
First of all i'd like to thank you for the fast reply! I really appreciate it.

I have a redmine installation behind a basic authentication system, the normal HTTP authentication you pointed on the screenshot. Reason for that is that I cannot afford to upgrade to new versions every time there is a security upgrade available, and since I give access only to a selected few, I feel safe from hack attacks.

This authentication layer is in frond of the real redmine-user authentication, and has nothing to do with user accounts. Its just a user/password pair to access the public redmine data (normally just a login form)

Thank you for your time

Stavros.

**Comment by matthiasblaesing** [comment]
Please check whether this pre-release helps (see the repository settings for the option to switch to accesskey + http-basic auth option):

https://github.com/redminenb/redminenb/wiki/redminenb-1.8.1-SNAPSHOT.nbm

This should do it:
- your pre-authentication is unlocked by http-basic auth and
- the real authentication is then done via the access key, that is supplied via the URL

**Comment by soraver** [comment]
Yes this worked for me :)
I'd prefere it to work with user/password too.
I mean it could not be limited to the api connection, but this worked for me.

Thank you very much!

**Comment by matthiasblaesing** [comment]
Thanks for testing!
