### ISSUE TITLE
Save Query is not working

### ISSUE THREAD

**Issue by workmonitored** [redminenb/redminenb#35]
I could not get it to save a query. I have tried removing the server and readding and various combinations after adding the query. Is there a way I can turn debug on to figure out what's going on? I am using jdk7 64 bit on windows 7 64 bit.

**Comment by matthiasblaesing** [comment]
How do you determine, that the query is not saved? Please test:

1. Invoke "Find taks" on the redmine entry in the services tab
2. configure your search and do a sample search
3. Click on "Save changes"
4. Specify a name
5. Make sure "Tasks" component is open and switch to it (Menu: Windows -> Tasks)
6. Your query is visible under Repositories -> your new repository

**Comment by workmonitored** [comment]
I do exactly what you suggest. Repositories is always open. The query gets
created under the redmine repository I create. I tried wiping out and
creating repository under a different name. The end result is the same. I
see query being created and then close Netbeans and come back.

The query is gone.

**Comment by matthiasblaesing** [comment]
Ok - while trying to reproduce I ran into a locking deadlock, which prevents me from opening a search once I created it (querying works, just not editing), it works for me:

![auswahl_001](https://cloud.githubusercontent.com/assets/2179736/7595494/bd3f735a-f8e7-11e4-873e-9a4db494eb40.png)

Please provide a screen shot of your tasks pane after you saved the query.

**Comment by workmonitored** [comment]
*Before*


*[image: Inline images 2]*

*Creating a Query*

**Comment by workmonitored** [comment]
*Query Creation *
[image: Inline images 2]

**Comment by workmonitored** [comment]
[image: Inline images 1]

**Comment by matthiasblaesing** [comment]
Your images did not make it to github

**Comment by workmonitored** [comment]
Before 
![image](https://cloud.githubusercontent.com/assets/7484771/7596499/f37f5074-f8a2-11e4-9dfc-4f5391389b6b.png)

**Comment by workmonitored** [comment]
During Query Creation.

![image](https://cloud.githubusercontent.com/assets/7484771/7596543/3ada98b6-f8a3-11e4-8a1b-a55f444d775f.png)

**Comment by workmonitored** [comment]
After closing and opening netbeans

![image](https://cloud.githubusercontent.com/assets/7484771/7596560/559b472c-f8a3-11e4-83fb-8b452fe6f524.png)

**Comment by workmonitored** [comment]
Saved it again on github. I can see them let me know if you cannot...

**Comment by workmonitored** [comment]
Could you please leave me instructions as to whether I can enable diagnostic logging or any such behaviour?

**Comment by matthiasblaesing** [comment]
Thank you for the screenshots, I wanted to be sure that we are talking about the same thing. Please provide the messages.log:

http://wiki.netbeans.org/FaqLogMessagesFile

The query you are creating: Is the query very complex?

**Comment by matthiasblaesing** [comment]
Another thing you can check: The query is saved as part of the preferences inside the netbeans userdir (http://wiki.netbeans.org/FaqWhatIsUserdir) the file is:

<userdir>/config/Preferences/com/kenai/redminenb.properties

**Comment by workmonitored** [comment]
om.taskadapter.redmineapi.NotAuthorizedException: Forbidden. Please check the user has proper permissions.
	at com.taskadapter.redmineapi.internal.comm.redmine.RedmineErrorHandler.processContent(RedmineErrorHandler.java:41)
	at com.taskadapter.redmineapi.internal.comm.redmine.RedmineErrorHandler.processContent(RedmineErrorHandler.java:21)
	at com.taskadapter.redmineapi.internal.comm.ComposingHandler.processContent(ComposingHandler.java:25)
	at com.taskadapter.redmineapi.internal.comm.ComposingHandler.processContent(ComposingHandler.java:25)
	at com.taskadapter.redmineapi.internal.comm.BaseCommunicator.sendRequest(BaseCommunicator.java:47)
	at com.taskadapter.redmineapi.internal.comm.redmine.RedmineAuthenticator.sendRequest(RedmineAuthenticator.java:52)
	at com.taskadapter.redmineapi.internal.comm.FmapCommunicator.sendRequest(FmapCommunicator.java:26)
	at com.taskadapter.redmineapi.internal.comm.FmapCommunicator.sendRequest(FmapCommunicator.java:26)
	at com.taskadapter.redmineapi.internal.comm.BasicSimplifier.sendRequest(BasicSimplifier.java:24)
	at com.taskadapter.redmineapi.internal.Transport.send(Transport.java:555)
	at com.taskadapter.redmineapi.internal.Transport.getChildEntries(Transport.java:481)
	at com.taskadapter.redmineapi.MembershipManager.getMemberships(MembershipManager.java:24)
[catch] at com.kenai.redminenb.repository.RedmineRepository.getUsers(RedmineRepository.java:448)
	at com.kenai.redminenb.query.RedmineQueryController$9.run(RedmineQueryController.java:529)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by workmonitored** [comment]
Not sure if above is the problem. I use the redmine server for my own sanity. I am surprised I am getting an exception on the getUsers...

**Comment by workmonitored** [comment]
I see a xml like but not quite file in it.

<redmineQuery version = "2">
    <parameters>
        <entry>
            <key>priority_id</key>
            <value>
                <item>
                    <displayName></displayName>
                    <value></value>
                </item>
            </value>
        </entry>
        <entry>
            <key>is_description</key>
            <value>
                <item>
                    <displayName></displayName>
                    <value></value>
                </item>
            </value>
        </entry>
        <entry>
            <key>query</key>
            <value>
                <item>
                    <displayName></displayName>
                    <value></value>
                </item>
            </value>
        </entry>
        <entry>
            <key>fixed_version_id</key>
            <value>
                <item>
                    <displayName></displayName>
                    <value></value>
                </item>
            </value>
        </entry>
        <entry>
            <key>project_id</key>
            <value>
                <item>
                    <displayName>WellPath</displayName>
                    <value>11</value>
                </item>
            </value>
        </entry>
        <entry>
            <key>watcher_id</key>
            <value>
                <item>
                    <displayName></displayName>
                    <value></value>
                </item>
            </value>
        </entry>
        <entry>
            <key>is_subject</key>
            <value>
                <item>
                    <displayName>1</displayName>
                    <value>1</value>
                </item>
            </value>
        </entry>
        <entry>
            <key>status_id</key>
            <value>
                <item>
                    <displayName>New</displayName>
                    <value>1</value>
                </item>
                <item>
                    <displayName>In Progress</displayName>
                    <value>2</value>
                </item>
            </value>
        </entry>
        <entry>
            <key>category_id</key>
            <value>
                <item>
                    <displayName></displayName>
                    <value></value>
                </item>
            </value>
        </entry>
        <entry>
            <key>tracker_id</key>
            <value>
                <item>
                    <displayName>Bug</displayName>
                    <value>1</value>
                </item>
                <item>
                    <displayName>Feature</displayName>
                    <value>2</value>
                </item>
                <item>
                    <displayName>Support</displayName>
                    <value>3</value>
                </item>
            </value>
        </entry>
        <entry>
            <key>assigned_to_id</key>
            <value>
                <item>
                    <displayName></displayName>
                    <value></value>
                </item>
            </value>
        </entry>
    </parameters>
</redmineQuery>

**Comment by matthiasblaesing** [comment]
The xml did not make it to github - please check the preview before sending a comment.

I still can't reproduce the problem - which version is the redmine installation you are running?

**Comment by matthiasblaesing** [comment]
No further reply - sorry I can't help.
