### ISSUE TITLE
SSL bug

### ISSUE THREAD

**Issue by gisupc** [redminenb/redminenb#37]
I use the netabeans8.0.2, C++,when use the redminenb,get error like this 
Cannot connect to Redmine:
java.lang.RuntimeException: Failed to connect; Cannot fetch data from https://redmine.XXXX.com/projects.json : javax.net.ssl.SSLException: Hostname did not verify

ref:https://kenai.com/projects/redminenb/pages/Home

**Comment by gisupc** [comment]
i use the latest redminenb v1.9

**Comment by matthiasblaesing** [comment]
My gut feeling:
- the ssl certificate is not valid for the host name you specify in the url (if you give the real url, I'll check)
- you don't have the SSL certificate exception module installed, that deals with that kind of situation: http://plugins.netbeans.org/plugin/53877/ssl-certificate-exception

**Comment by matthiasblaesing** [comment]
No reply after two weeks - I'll asume the hints fixed your problem. Closing this for now.
