### ISSUE TITLE
SSL SNI Issue

### ISSUE THREAD

**Issue by magno32** [redminenb/redminenb#39]
This may be related to the closed #37.

I am also having an issue with our certificate, which is correct (verified) in web-browsers.  

I don't know much about SSL so my wording may be off.
When we tested with the ```openssl s_client```, the wrong certificate was in fact being presented for our tracker, we were getting a certificate from the default VHost on the server.  Using the ```-servername ``` flag, openssl returns the proper certificate for that VHost.

Is it possible that redminenb is not using SNI to get the correct certificate from the server?

FWIW, the SSL Exception plugin is a workaround, but the certificate that we should be getting from the redmine plugin is valid.

**Comment by matthiasblaesing** [comment]
yes - redminenb is not using SNI. The cause can be found in a very old apache http client library. I updated the bundled library to use a newer httpclient library which should fix this problem.

If you can, feel free to build from git head, this contains the necessary fix.

**Comment by magno32** [comment]
Thanks for the update. 

I was able to build and get this working with the following change to the redminnb pom:
```patch
diff --git a/dev/pom.xml b/dev/pom.xml
index 0dfeca7..4449a40 100644
--- a/dev/pom.xml
+++ b/dev/pom.xml
@@ -39,6 +39,7 @@
         <brandingToken>redminenb</brandingToken>
         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
         <netbeans.run.params>-J-Dnetbeans.full.hack=true</netbeans.run.params>
+		<httpcomponents.version>4.4.1</httpcomponents.version>
     </properties>
 
     <dependencies>
@@ -166,6 +167,18 @@
             <version>3.0.0</version> 
             <scope>provided</scope> 
         </dependency>
+		<dependency>
+			<groupId>org.apache.httpcomponents</groupId>
+			<artifactId>httpclient</artifactId>
+			<version>${httpcomponents.version}</version>
+			<type>jar</type>
+		</dependency>
+		<dependency>
+			<groupId>org.apache.httpcomponents</groupId>
+			<artifactId>httpcore</artifactId>
+			<version>${httpcomponents.version}</version>
+			<type>jar</type>
+		</dependency>
     </dependencies>
 
     <build>
```

**Comment by matthiasblaesing** [comment]
Yes you change should do it - however I upgraded the bundled redmine library and the internal usage and if possible I'd like to ask you to test:

https://github.com/redminenb/redminenb/wiki/redminenb-1.10.1-SNAPSHOT.nbm

That is a build from latest git HEAD.

**Comment by musiKk** [comment]
Thanks a lot. I was just running into this issue and your linked 1.10.2-SNAPSHOT fixes it.

**Comment by matthiasblaesing** [comment]
Thank you for testing - I just pushed a release from this.
