### ISSUE TITLE
javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by GothicChris** [redminenb/redminenb#44]
I can't connect with my Redmine 3.0 over HTTPS with Port 3712.

Redmine is running on Port 3712 an HTTPS. 

when i try to connect, i get the following message:

```
Cannot connect to Redmine:
java.lang.RuntimeException: Failed to connect; Cannot fetch data from https://my.domain.de:3712/users/current.json : javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

The Certicate on the Server ist trusted by Deutsche Telekom.

**Comment by matthiasblaesing** [comment]
Without further information (the domain name for example) I can only speculate: The root certificate is not part of the java certificate store or the server does not deliver the whole certificate chain.

Just to be sure: Which java, netbeans and redmine-nb version are you using? Can you provide the complete message.log for the session?

**Comment by GothicChris** [comment]
The full Redmine domain name: https://pi.inf.ik.w-hs.de:3712

java version "1.8.0_31"
Redmine 8.01
Redmine-NB 1.11

Where can i found the message.log? The exception is only showing in the textarea, where i can add a new Redmine configuration.

**Comment by matthiasblaesing** [comment]
You won't need the message.log - I just tried to open the URL with firefox and well the certificate chain is broken or to be more precise: not existing. 

When the connection is opened the server presents exactly one certificate and this is not part of the java truststore and there is the root of your problem. It is strongly advised to let server always send the whole certificate chain until the root-CA is reached. This way only the root-CA needs to be present in the truststore.

To have a look at the certificate chain - open the URL you provided with a firefox - if the site is not yet trusted you will be presented with "Dieser Verbindung wird nicht vertraut"-error message (I run my firefox in german locale), there you can choose "Ich kenne das Risiko" and choose "Ausnahme hinzufügen". In the following dialog choose "Zertifikat herunterladen" and then "Ansehen". In the "Details" the certificates are listed - coming from outside only one certificate is listed - that for the server.

That certificate is signed by "CA der Westfaelischen Hochschule - G01", this CA certificate is most probably signed by the DFN and that certificate is signed by "Deutsche Telekom" (if I remember the hierarchy completely). The only safe certificate in that chain I would expect in the truststore is the certificate of "Deutsche Telekom". Indeed looking into the certificate store of my firefox instance I see several university CAs that show this hierarchy.

My advise: Fix the server, the configuration is broken.

If you are in the situation this can't be done: 

* Best option: Import the server certifacate or the CA certificate into the java truststore or
* Easier option: Install the ["SSL Certificate Exception"](http://plugins.netbeans.org/plugin/53877/ssl-certificate-exception) plugin - this allows you to add exceptions to the SSL checking algorithm. I just checked the plugin is only marked for 8.0, but it works on 8.1 as it should.

Please check if this helps you.

PS: Your java version is _old_ current is 1.8.0_66

**Comment by GothicChris** [comment]
Thanks for the informations. 

i will fix the server to send the whole certificate chain. i think that is only an apache configuration problem.

**Comment by svatos-jirka** [comment]
You have to install certficate from server to your java.

keytool -import -alias redmineSiemens -file "E:\SiemensIssuingCAIntranetServer2013.crt" -keystore "e:\Program Files\Java\
jdk1.8.0_101\jre\lib\security\cacerts"
default passwor for java cacern is "changeit"
