### ISSUE TITLE
Not latini symbols;

### ISSUE THREAD

**Issue by eof273** [redminenb/redminenb#46]
Not saved issues with not "en" locale symbols (russian - фйяч, spanish - úáÉ, chinese, etc).
![cyrillic](https://cloud.githubusercontent.com/assets/18496223/14579739/7053cb1e-03f8-11e6-8845-3185d8db411f.gif)

Redmine system don't have problem with it:
![ch](https://cloud.githubusercontent.com/assets/18496223/14579751/141ec5c8-03f9-11e6-905a-e1a544437060.JPG)
![es](https://cloud.githubusercontent.com/assets/18496223/14579752/141f1c80-03f9-11e6-9021-88e3e16dadf8.JPG)
![ru](https://cloud.githubusercontent.com/assets/18496223/14579753/142139c0-03f9-11e6-99df-d5642e9be2f7.JPG)

**Comment by matthiasblaesing** [comment]
Plase give: redmine version, java version, netbeans version oh and OS -- I can't reproduce your problem:

This is: Java 8 (a build from mercurial head some months ago), Redmine 3.0.4, netbeans 8.1 on linux (ubuntu).

![auswahl_001](https://cloud.githubusercontent.com/assets/2179736/14580828/6387509e-03db-11e6-9f18-9c3608bcc8fc.png)

![auswahl_002](https://cloud.githubusercontent.com/assets/2179736/14580831/8db3d9f0-03db-11e6-928a-c25ba2c54585.png)

**Comment by eof273** [comment]
_Info_:
**Product Version**: NetBeans IDE 8.0.2 (Build 201411181905)
**Update**: NetBeans 8.0.2 Patch 2
**Java**: 1.8.0_45; Java HotSpot(TM) 64-Bit Server VM 25.45-b02
**Runtime**: Java(TM) SE Runtime Environment 1.8.0_45-b14
**System**: Windows 7 version 6.1 running on amd64; UTF-8; ru_RU (nb)

**Redmine**: 1.4.4.stable (MySQL)

_Error log_:
`org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at com.taskadapter.redmineapi.internal.RedmineJSONParser.getResponseSingleObject(RedmineJSONParser.java:705)
	at com.taskadapter.redmineapi.internal.Transport.parseResponse(Transport.java:584)
Caused: com.taskadapter.redmineapi.RedmineFormatException
	at com.taskadapter.redmineapi.internal.Transport.parseResponse(Transport.java:586)
	at com.taskadapter.redmineapi.internal.Transport.addObject(Transport.java:225)
	at com.taskadapter.redmineapi.IssueManager.createTimeEntry(IssueManager.java:271)
	at com.kenai.redminenb.issue.RedmineIssuePanel$16.doInBackground(RedmineIssuePanel.java:1664)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[catch] at java.lang.Thread.run(Thread.java:745)
`

**Comment by matthiasblaesing** [comment]
This redmine version is ancient and I suspect the unicode/json handling is just broken in the old version. If you get me a network trace of the request I'll check the wire level, but the reply looks broken.

**Comment by eof273** [comment]
Sorry for stupid question, but how I can see request from NB plugin to Redmine?

**Comment by matthiasblaesing** [comment]
Not so stupid question - you either need an interceptor on the network connection (wireshark/owasp proxy) or get apache http client to log the information:

0. Ensure, that in the following no sensitive information is transfered to/from redmine (the password should be throw away, the data only testdata!)
1. Install the "Log Management" plugin: http://plugins.netbeans.org/plugin/3551/log-management
2. Connect to the redmine repository
3. In the netbeans "Services" tab, under the "Registered Loggers" node, you'll find the node "org.apache.http.wire" (if not, ensure, that you connected to redmine and choose refresh on the "Registered Loggers" tab
4. Choose properties for the "org.apache.http.wire" node and change the logger level to "FINE"
5. Choose "View" in the context menu of the node

After that an output window will open, showing the wire protocol - now you can reissue the problematic query, the request will be logged and can be copy/pasted.

**Comment by eof273** [comment]
Thank You for answer!
**Request for new issue** (Subject = `Subject - Заголовок;`, Description = `Description - Описание;`):

    {
      "issue" : {
        "subject" : "Subject - [0xd0][0x97][0xd0][0xb0][0xd0][0xb3][0xd0][0xbe][0xd0][0xbb][0xd0][0xbe][0xd0][0xb2][0xd0][0xbe][0xd0][0xba];",
        "parent_issue_id" : null,
        "estimated_hours" : null,
        "assigned_to_id" : 1,
        "priority_id" : 4,
        "done_ratio" : 0,
        "project_id" : 2,
        "start_date" : null,
        "due_date" : null,
        "tracker_id" : 1,
        "description" : "Description - [0xd0][0x9e][0xd0][0xbf][0xd0][0xb8][0xd1][0x81][0xd0][0xb0][0xd0][0xbd][0xd0][0xb8][0xd0][0xb5];",
        "status_id" : 1,
        "fixed_version_id" : null,
        "category_id" : null
      }
    }

**Request for update issue**:

    {
      "issue" : {
        "id" : 5,
        "subject" : "Subject - [0xd0][0x97][0xd0][0xb0][0xd0][0xb3][0xd0][0xbe][0xd0][0xbb][0xd0][0xbe][0xd0][0xb2][0xd0][0xbe][0xd0][0xba];",
        "parent_issue_id" : null,
        "estimated_hours" : null,
        "assigned_to_id" : 1,
        "priority_id" : 3,
        "done_ratio" : 100,
        "project_id" : 1,
        "start_date" : null,
        "due_date" : null,
        "tracker_id" : 1,
        "description" : "Description - [0xd0][0x9e][0xd0][0xbf][0xd0][0xb8][0xd1][0x81][0xd0][0xb0][0xd0][0xbd][0xd0][0xb8][0xd0][0xb5];",
        "status_id" : 3,
        "fixed_version_id" : null,
        "category_id" : null
      }
    }

Full logs (not contain confidential information, cause it test local server with admin\admin log.\pass.):
[Create.txt](https://github.com/redminenb/redminenb/files/222230/Create.txt)
[Update.txt](https://github.com/redminenb/redminenb/files/222231/Update.txt)

**Comment by matthiasblaesing** [comment]
This one points to the problem - in the update log you see entry 11, this one contains the request (you already extracted that. The request itself looks good, apache http client writes the byte sequences outside the ascii range as hexadecimals. For the chars outside the ascii range UTF-8 (the JSON charset), the encoding becomes multi-byte, [0xd0][0x97] is ```CYRILLIC CAPITAL LETTER ZE``` ([Table](http://www.utf8-zeichentabelle.de/unicode-utf8-table.pl?start=1024&number=128&utf8=0x)). I did not check every entry, but they look sane.

The server then returns a ```500 internal server error```. So this would be the moment to either check a newer installation or the server log.

**Comment by eof273** [comment]
`incompatible character encodings: UTF-8 and ASCII-8BIT`
You right, problem in server configuration.  I will continue working on this.
Thanks for Your answers & this plugin. Its really helpful;
