### ISSUE TITLE
Racecondition while retrieving category/version data

### ISSUE THREAD

**Issue by Sh4d0wF1gh7** [redminenb/redminenb#47]
Hello,
i´m not sure if my "bug" is same as the other post. Just do a separate one.
I use your Netbeans Plugin with current Redmine 3.3.0 and it works but if i open a ticket with a target-version, this value is not read out correctly and is empty. if we do now an update of the task, the target-version is written empty and lose version.
This happens only sometimes.
Mostly with another click on the blue refresh button on top right, the version is read correctly.
Can you see this also?
Greets

**Comment by matthiasblaesing** [comment]
The target version is resolved from the project, so when you switch projects and the selected project does not contain the version, the version will be cleared. I don't see a race condition in the code - basicly you need to switch projects to reinitialize the list.

Please check if this is your case or if you can further pin-point the issue. Feel free to reopen this then.

**Comment by matthiasblaesing** [comment]
Reopening this, as I can reproduce something similar:
- Fresh start
- Open issue with a set category and version
- Observation: issue is opened without version+category

I have to see where this comes from.

**Comment by matthiasblaesing** [comment]
@Sh4d0wF1gh7 can you test the changes I pushed a few seconds ago? Please indicate if you can't build from source, I'll provide pre-built binaries then.

**Comment by Sh4d0wF1gh7** [comment]
Hello,
yes this would be great if you can provide me an installable netbeans plugin.
I´ll test it immediately...

**Comment by matthiasblaesing** [comment]
You can find a test version here:
https://github.com/redminenb/redminenb/wiki/redminenb-1.11.1.nbm

**Comment by Sh4d0wF1gh7** [comment]
Yes, works like a charme... Thank you very much...
