### ISSUE TITLE
Netbeans 8.2 SSLHandshakeException

### ISSUE THREAD

**Issue by RolandSM** [redminenb/redminenb#54]
Hello,
today i tried to integrate Redmine into new Netbeans 8.2 and get only following error:

> Cannot connect to Redmine:
java.lang.RuntimeException: Failed to connect; Cannot fetch data from https://redmine.mydomain.de/users/current.json : javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

In Netbeans 8.1 all is ok?

**Comment by matthiasblaesing** [comment]
I'll guess that this is not so much an issue with netbeans 8.2, but with the used certificate store. To get SSL support you need a valid certificate path from a root certificate to the certificate used by the webserver offering the redmine repository. This is not the case here.

I had a look at your certificate chain and it is indeed problematic. Mozilla and some other browser vendors decided not to trust startcom certificates any longer. Maybe oracle followed that motion and also disabled the support. So there are two options:

1. Modify the truststore.jks of your java installation and add the startcom root certificate or
2. Use this netbeans plugin: http://plugins.netbeans.org/plugin/53877/ssl-certificate-exception . This allows you to add exceptions for sites.

**Comment by RolandSM** [comment]
Hello,
i have installed the ssl-certificate-exception in netbeans 8.2. also it was installed on 8.1
Think there was a question if i want to trust? Yes thats right.
In meantime, the certificate is Lets encrypt and now both, netbeans 8.1 and netbeans 8.2 cant connect.
Also there comes no further question, perhaps a decition exists from old certificate?
I´m on a ubuntu system, don´t know where i can add the truststore.jks or where i can remove existing exceptions???

Some news showing for reason:
javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair

**Comment by matthiasblaesing** [comment]
Move to a recent JDK (fix version 8.0u56): http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7044060

or install the unlimited JCE packages (if I'm correctly informed Java 9 will be unlimited by default): http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by RolandSM** [comment]
Hello and thank you, now i use the systems Java home in the netbeans.conf.
Java 9 throws errors on ntebeans start but Java 8 current version works.

**Comment by matthiasblaesing** [comment]
Java 9 is Work in Progress - there is no reason to expect anything to work correctly at this point and no reason to open an issue.
